[package]
name = "ppppong"
version = "0.0.1"
authors = ["fricze andrzej.fricze@gmail.com"]
edition = "2018"
description = "PPPPPOOOOONG"
license = "MIT"

[dependencies]
ggez = "0.6.0-rc0"
glam = { version = "0.12", features = ["mint"]}
